// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBowbxNwtg5KrmREanChaVjKDiBMGu5VBA',
    appId: '1:57240731041:web:0c7b7bd6dc96f19f29dfe0',
    messagingSenderId: '57240731041',
    projectId: 'flutter-app-40a5f',
    authDomain: 'flutter-app-40a5f.firebaseapp.com',
    storageBucket: 'flutter-app-40a5f.appspot.com',
    measurementId: 'G-ZCVXPZBP8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zPnQsPvaliGVkZk-G-KvyN8e9Oc1c4k',
    appId: '1:57240731041:android:e5d18544fc249a1629dfe0',
    messagingSenderId: '57240731041',
    projectId: 'flutter-app-40a5f',
    storageBucket: 'flutter-app-40a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLNYaEpjs9GKhpAHNJ8cSgeZ9iPaqxizY',
    appId: '1:57240731041:ios:9e91d110eaefa14729dfe0',
    messagingSenderId: '57240731041',
    projectId: 'flutter-app-40a5f',
    storageBucket: 'flutter-app-40a5f.appspot.com',
    iosClientId: '57240731041-5d2h7ieqbhrd8k56e312jq1295uac24e.apps.googleusercontent.com',
    iosBundleId: 'com.wasem.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLNYaEpjs9GKhpAHNJ8cSgeZ9iPaqxizY',
    appId: '1:57240731041:ios:e765429eaaf691aa29dfe0',
    messagingSenderId: '57240731041',
    projectId: 'flutter-app-40a5f',
    storageBucket: 'flutter-app-40a5f.appspot.com',
    iosClientId: '57240731041-36jp524j0stl1eud6pdqetn7k03r4lte.apps.googleusercontent.com',
    iosBundleId: 'com.wasem.firebaseApp.RunnerTests',
  );
}
